<?php
return [
	'chapter1' => 'The Coming of the Ship',
	'chapter2' => 'Love',
	'chapter3' => 'Marriage',
	'chapter4' => 'Children',
	'chapter5' => 'Giving',
	'chapter6' => 'Eating and Drinking',
	'chapter7' => 'Work',
	'chapter8' => 'Joy and Sorrow',
	'chapter9' => 'Houses',
	'chapter10' => 'Clothes',
	'chapter11' => 'Buying and Selling',
	'chapter12' => 'Crime and Punishment',
	'chapter13' => 'Laws',
	'chapter14' => 'Freedom',
	'chapter15' => 'Reason and Passion',
	'chapter16' => 'Pain',
	'chapter17' => 'Self-Knowledge',
	'chapter18' => 'Teaching',
	'chapter19' => 'Friendship',
	'chapter20' => 'Talking',
	'chapter21' => 'Time',
	'chapter22' => 'Good and Evil',
	'chapter23' => 'Prayer',
	'chapter24' => 'Pleasure',
	'chapter25' => 'Beauty',
	'chapter26' => 'Religion',
	'chapter27' => 'Death',
	'chapter28' => 'The Farewell',
];
?>